services:
  - type: web
    name: budget-backend
    env: python
    buildCommand: ""
    startCommand: python src/main.py
    envVars:
      - key: FLASK_ENV
        value: production
    region: oregon