databases:
  - name: expense_tracker_db
    databaseName: expense_tracker_db
    user: expense_tracker_user
    plan: free

services:
  - type: web
    name: expense_tracker_api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense_tracker_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
